In [1]:
# 3-Layer Network adding five numbers
# Abraham Oliver, 2016
# ReverseLearning

In [2]:
# Imports
import tensorflow as tf
import numpy as np
from random import random
from random import randint
from math import sin

# Import python3's print as a function
from __future__ import print_function

# Numpy print options
np.set_printoptions(precision = 3, suppress = True)

In [3]:
# Initiate Session
sess = tf.InteractiveSession()

In [7]:
# Network to add five float inputs
# 5 Input, 3 Hidden, 1 Output

# Input
inp = tf.placeholder(tf.float32, [None, 5])
# Input Weights
w1 = tf.Variable(tf.zeros([5, 3]))
# Input Biases
b1 = tf.Variable(tf.ones([3]))
# Input's Output, Hidden's Input
out1 = tf.matmul(inp, w1) + b1

# Hidden weights
w2 = tf.Variable(tf.zeros([3, 1]))
# Hidden biases
b2 = tf.Variable(tf.ones([1]))
# Output
out = tf.matmul(out1, w2) + b2

# Label
lbl = tf.placeholder(tf.float32, [None, 1])

# Training with quadratic cost and gradient descent with learning rate .01
loss = tf.pow(tf.reduce_mean(lbl - out), 2)
train_step = tf.train.ProximalGradientDescentOptimizer(0.01).minimize(loss)

In [9]:
# Train and run normal network

# Initialize variables
sess.run(tf.initialize_all_variables())

# Make data set of three inputs and their output
def newSet(size, inputs = 5):
    data = []
    labels = []
    for s in range(size):
        newInputs = [random() * randint(-100, 100) for i in range(inputs)]
        data.append(newInputs)
        labels.append([sum(newInputs)])
    return (data, labels)

# Train normal model
DEBUG = True
for i in range(2001):
    batch_inps, batch_outs = newSet(200)
    if i % 2000 == 0 and DEBUG:
        print("Weights1 :: \n{0}".format(w1.eval()))
        print("Biases1 :: {0}".format(b1.eval()))
        print("Weights2 :: \n{0}".format(w2.eval()))
        print("Biases2 :: {0}".format(b2.eval()))
        print("Loss :: {0}\n".format(loss.eval(feed_dict={inp: batch_inps, lbl: batch_outs})))
    sess.run(train_step, feed_dict={inp: batch_inps, lbl: batch_outs})

def compute(INPUT):
    return round(out.eval(feed_dict={inp: INPUT})[0])

print("1 + 1 + 1 + 1 + 1 = {0}".format(compute([[1, 1, 1, 1, 1]])))
print("10 + 10 + 10 + 10 + 10 = {0}".format(compute([[10, 10, 10, 10, 10]])))
print("100 + 100 + 100 + 100 + 100 = {0}".format(compute([[100, 100, 100, 100, 100]])))

Weights1 :: 
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Biases1 :: [ 1.  1.  1.]
Weights2 :: 
[[ 0.]
 [ 0.]
 [ 0.]]
Biases2 :: [ 1.]
Loss :: 49.9417266846

Weights1 :: 
[[-0.533 -0.533 -0.533]
 [-0.533 -0.533 -0.533]
 [-0.533 -0.533 -0.533]
 [-0.533 -0.533 -0.533]
 [-0.533 -0.533 -0.533]]
Biases1 :: [ 0.652  0.652  0.652]
Weights2 :: 
[[-0.625]
 [-0.625]
 [-0.625]]
Biases2 :: [ 1.222]
Loss :: 5.13871497437e-13

1 + 1 + 1 + 1 + 1 = 5.0
10 + 10 + 10 + 10 + 10 = 50.0
100 + 100 + 100 + 100 + 100 = 500.0


In [11]:
# Save paramaters and close session
saved_weights1 = w1.eval()
saved_weights2 = w2.eval()
saved_biases1 = b1.eval()
saved_biases2 = b2.eval()
sess.close()

In [12]:
#INPUT BACKPROP

In [13]:
# Start new session for input backprop
sess = tf.InteractiveSession()

In [15]:
# 5 Free Inputs

# Objective: Get five inputs that sum to 'VAL'
VAL = 14.0

# Input
optimal = tf.Variable(tf.zeros([1, 5]))
# Input Weights
w1 = tf.constant(saved_weights1)
# Input Biases
b1 = tf.constant(saved_biases1)
# Input's Output
out1 = tf.matmul(optimal, w1) + b1

# Hidden Weights
w2 = tf.constant(saved_weights2)
# Hidden Biases
b2 = tf.constant(saved_biases2)
# Ouput
out = tf.matmul(out1, w2) + b2

# Label
lbl = tf.constant([VAL])

# Training with quadratic cost and gradient descent with learning rate .01
loss = tf.pow(tf.reduce_mean(lbl - out), 2)
train_step = tf.train.ProximalGradientDescentOptimizer(0.01).minimize(loss)

# Initialize variables
sess.run(tf.initialize_all_variables())

# Train to find three inputs
for i in range(400):
    sess.run(train_step)

print("INPUTS :: {0}".format(optimal.eval()))
print("LOSS   :: {0}".format(loss.eval()))

INPUTS :: [[ 2.8  2.8  2.8  2.8  2.8]]
LOSS   :: 3.27418092638e-11


In [18]:
# 3 Free, 2 Set Inputs

# Objective: Get five inputs that sum to 'VAL' where one input is 'INP1' and another is 'INP2'
VAL = 20.0
INP1 = 5.0
INP2 = 3.0

# Inputs
optimal = tf.Variable(tf.zeros([1, 3]))
# Input Weights
w1 = tf.constant(saved_weights1)
# Input Biases
b1 = tf.constant(saved_biases1)
# Input's Output
out1 = tf.matmul(optimal, w1[:3]) + tf.matmul([[INP1, INP2]], w1[3:]) + b1

# Hidden weights
w2 = tf.constant(saved_weights2)
# Input Biases
b2 = tf.constant(saved_biases2)
# Input's Output
out = tf.matmul(out1, w2) + b2

# Label
lbl = tf.constant([VAL])

# Training with quadratic cost and gradient descent with learning rate .01
loss = tf.pow(tf.reduce_mean(lbl - out), 2)
train_step = tf.train.ProximalGradientDescentOptimizer(0.01).minimize(loss)

# Initialize variables
sess.run(tf.initialize_all_variables())

# Train to find three inputs
for i in range(800):
    sess.run(train_step)

print("INPUTS :: {0}".format((str(optimal.eval()), INP1, INP2)))
print("LOSS   :: {0}".format(loss.eval()))

INPUTS :: ('[[ 4.  4.  4.]]', 5.0, 3.0)
LOSS   :: 3.27418092638e-11
