In [1]:
# Small Networks for Experiments
# Abraham Oliver, 2016
# ReverseLearning

In [2]:
# Imports
import tensorflow as tf
import numpy as np
from random import random
from random import randint
from math import sin

# Import python3's print as a function
from __future__ import print_function

# Numpy print options
np.set_printoptions(precision = 3)

In [3]:
# Initiate Session
sess = tf.InteractiveSession()

In [26]:
# Network to add three float inputs
# 3 Input, 1 Output

# Input
inp = tf.placeholder(tf.float32, [None, 3])
# Input Weights
w = tf.Variable(tf.zeros([3, 1]))
# Input Biases
b = tf.Variable(tf.ones([1]))
# Output
out = tf.matmul(inp, w) + b
# Label
lbl = tf.placeholder(tf.float32, [None, 1])

# Training with quadratic cost and gradient descent with learning rate .5
#loss = tf.pow(tf.reduce_mean(lbl - out), 2)
loss = tf.reduce_mean(-tf.reduce_sum(lbl * tf.log(out), reduction_indices = [1]))
train_step = tf.train.ProximalGradientDescentOptimizer(0.01).minimize(loss)

In [20]:
# Input backprop model

# Optimal Input variable (Only one item, unlike unknown above)
optimal = tf.Variable(tf.zeros([1, 3]))
# Predicted Output
predicted = tf.nn.softmax(tf.matmul(optimal, w) + b)
# Output to recreate
output = tf.placeholder(tf.float32, [1])

# Training functions
optimal_train_loss = tf.reduce_mean(-tf.reduce_sum(output * tf.log(predicted), reduction_indices = [1]))
optimal_train_step = tf.train.ProximalGradientDescentOptimizer(0.5).minimize(optimal_train_loss)

In [27]:
# Train and run normal network

# Initialize variables
sess.run(tf.initialize_all_variables())

# Make data set of three inputs and their output
def newSet(size, inputs = 3):
    data = []
    labels = []
    for s in range(size):
        newInputs = [random() * randint(-100, 100) for i in range(inputs)]
        data.append(newInputs)
        labels.append([sum(newInputs)])
    return (data, labels)

# Train normal model
DEBUG = True
for i in range(2001):
    batch_inps, batch_outs = newSet(100)
    if i % 2000 == 0 and DEBUG:
        print("Weights :: \n{0}".format(w.eval()))
        print("Biases :: {0}".format(b.eval()))
        print("Loss :: {0}\n".format(loss.eval(feed_dict={inp: batch_inps, lbl: batch_outs})))
    sess.run(train_step, feed_dict={inp: batch_inps, lbl: batch_outs})

def compute(INPUT):
    return round(out.eval(feed_dict={inp: INPUT})[0])

Weights :: 
[[ 0.]
 [ 0.]
 [ 0.]]
Biases :: [ 1.]
Loss :: 0.0

Weights :: 
[[ 18.101]
 [ 16.283]
 [ 11.175]]
Biases :: [ 2.683]
Loss :: nan



In [28]:
print("1 + 1 + 1 = {0}".format(compute([[1, 1, 1]])))
print("10 + 10 + 10 = {0}".format(compute([[10, 10, 10]])))
print("100 + 100 + 100 = {0}".format(compute([[100, 100, 100]])))
print("1000 + 1000 + 1000 = {0}".format(compute([[1000, 1000, 1000]])))
print("10000 + 10000 + 10000 = {0}".format(compute([[10000, 10000, 10000]])))
print("WEIGHTS :: \n{0}".format(w.eval()))
print("BIASES  :: {0}".format(b.eval()))

1 + 1 + 1 = 48.0
10 + 10 + 10 = 458.0
100 + 100 + 100 = 4558.0
1000 + 1000 + 1000 = 45555.0
10000 + 10000 + 10000 = 455524.0
WEIGHTS :: 
[[ 18.099]
 [ 16.28 ]
 [ 11.173]]
BIASES  :: [ 2.683]
